language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - platform-tools
    - extra-android-support
    - sys-img-armeabi-v7a-android-26

sudo: true

before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)